In [1]:
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
import numpy as np

vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
import numpy as np

array = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(array)

print(indices)

(array([0, 1, 4], dtype=int64),)


In [5]:
import numpy as np
array = np.random.random((10, 10))

minimum = np.min(array)
maximum = np.max(array)

print("Minimum value:", minimum)
print("Maximum value:", maximum)


Minimum value: 0.029092103128206315
Maximum value: 0.9983625294591149


In [6]:
import numpy as np

random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)

print("Random vector:", random_vector)
print("Mean value:", mean_value)

Random vector: [0.98857417 0.52913141 0.80791997 0.42280731 0.47455515 0.6247402
 0.18750848 0.78272225 0.05337191 0.06920713 0.79214285 0.57054746
 0.63961052 0.93488243 0.6148481  0.17593292 0.01592968 0.15891814
 0.9496938  0.33751308 0.65802713 0.97738737 0.27069191 0.03174832
 0.55667474 0.64037995 0.70838041 0.87950106 0.37466371 0.14575365]
Mean value: 0.5124588400046068
